import {
  AlinexOne,
  NewsOne
} from "../assets/images/index";

export const productFeatureTitle = {
  color: "Цвет",
  dryingTime: "Время высыхания",
  waterproof: "Водостойкость",
  mixingRatio: "Соотношение смешивания",
  maxGrainSize: "Максимальный размер зерна",
  materialClass: "Максимальная крупность наполнителя",
  mobilityClass: "Класс мобильности",
  strengthClass: "Класс прочности",
  frostResistance: "Морозостойкость",
  adhesionStrength: "Прочность сцепления",
  effectiveActivity: "Удельная эффективная активность ЕРН (Аэфф)",
  compressiveStrength: "Прочность на сжатие",
  materialConsumption: "Расход материала",
  applicationTemperature: "Температура применения",
  solutionViability: "Жизнеспособность раствора",
}

export const navBarList = [
  {
    _id: 1001,
    title: "Главный",
    link: "/",
  },
  {
    _id: 1002,
    title: "Каталог",
    link: "/catalog",
  },
  {
    _id: 1003,
    title: "О компании",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Контакты",
    link: "/contact",
  },
  {
    _id: 1005,
    title: "Блог/Новости",
    link: "/news",
  },
];

export const SplOfferData = [
  {
    _id: "201",
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "35.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "202",
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "180.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "25.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "220.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];

export const paginationItems = [
  {
    _id: 1001,
    img: AlinexOne,
    productName: "Декоративная штукатурка c нанесением «Леонардо» и «Травертин» AlinEX «FORTRESS», 25 кг",
    price: "35.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1002,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "180.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1003,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "25.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1004,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "220.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1005,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "35.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1006,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "180.00",
    color: "Штукатурки",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1007,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "25.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1008,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "220.00",
    color: "Штукатурки",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1009,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "44.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1010,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "250.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1011,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "80.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1012,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "60.00",
    color: "Штукатурки",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1013,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "60.00",
    color: "Штукатурки",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

  {
    _id: 1014,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "250.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1015,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "60.00",
    color: "Штукатурки",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1016,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "250.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1017,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "220.00",
    color: "Штукатурки",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1018,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "44.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1019,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "250.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1020,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "80.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1021,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "25.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1022,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "220.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1023,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "35.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1024,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "35.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1025,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "180.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1026,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "25.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1027,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "220.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1028,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "35.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1029,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "180.00",
    color: "Штукатурки",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1030,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "25.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1031,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "220.00",
    color: "Штукатурки",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1032,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "44.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1033,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "250.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1034,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "80.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1035,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "60.00",
    color: "Штукатурки",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1036,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "60.00",
    color: "Штукатурки",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1037,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "60.00",
    color: "Штукатурки",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1038,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "250.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1039,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "220.00",
    color: "Штукатурки",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1040,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "44.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1041,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "250.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1042,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "80.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1043,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "25.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1044,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "220.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1045,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "35.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1046,
    img: AlinexOne,
    productName: "Гипсовая штукатурка",
    price: "35.00",
    color: "Штукатурки",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];

export const paginationItemsForNews = [
  {
    _id: 1001,
    date: "10 октября 2024",
    img: NewsOne,
    previewImg: NewsOne,
    title: "Мы открылись!",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.  " +
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis."
  },
  {
    _id: 1002,
    date: "10 октября 2024",
    img: NewsOne,
    previewImg: NewsOne,
    title: "Мы открылись!",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.  "
  },
  {
    _id: 1003,
    date: "10 октября 2024",
    img: NewsOne,
    previewImg: NewsOne,
    title: "Мы открылись!",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.  "
  },
  {
    _id: 1004,
    date: "10 октября 2024",
    img: NewsOne,
    previewImg: NewsOne,
    title: "Мы открылись!",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.  "
  },
  {
    _id: 1005,
    date: "10 октября 2024",
    img: NewsOne,
    previewImg: NewsOne,
    title: "Мы открылись!",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.  "
  },
  {
    _id: 1006,
    date: "10 октября 2024",
    img: NewsOne,
    previewImg: NewsOne,
    title: "Мы открылись!",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.  "
  },
  {
    _id: 1007,
    date: "10 октября 2024",
    img: NewsOne,
    previewImg: NewsOne,
    title: "Мы открылись!",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.  "
  },
  {
    _id: 1008,
    date: "10 октября 2024",
    img: NewsOne,
    previewImg: NewsOne,
    title: "Мы открылись!",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.  "
  },
  {
    _id: 1009,
    date: "10 октября 2024",
    img: NewsOne,
    previewImg: NewsOne,
    title: "Мы открылись!",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.  "
  },
  {
    _id: 1010,
    date: "10 октября 2024",
    img: NewsOne,
    previewImg: NewsOne,
    title: "Мы открылись!",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.  "
  },
  {
    _id: 1011,
    date: "10 октября 2024",
    img: NewsOne,
    previewImg: NewsOne,
    title: "Мы открылись!",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.  "
  },
  {
    _id: 1012,
    date: "10 октября 2024",
    img: NewsOne,
    previewImg: NewsOne,
    title: "Мы открылись!",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.  "
  }
];
